api_platform:
  title: Hello API Platform
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]

  formats:
    jsonld: ["application/ld+json"]
    json: [ "application/json" ]
    graphql: ['application/graphql']

  patch_formats:
    json: [ "application/merge-patch+json" ]

  graphql:
    graphiql:
      enabled: true
    graphql_playground:
      enabled: true