framework:
  cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include:

    # Redis
    #        app: cache.adapter.redis
    #        default_redis_provider: '%env(resolve:REDIS_URL)%'

    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu

    # Namespaced pools use the above "app" backend by default
    #pools:
    #my.dedicated.cache: null
    pools:
      cache.redis:
        default_lifetime: 31536000  # One year
        adapters:
          - cache.adapter.array
          - cache.adapter.apcu
          - { name: cache.adapter.redis, provider: app.redis_provider }
#                adapter: cache.adapter.redis
#                provider: app.redis_provider
